# Generated by Django 5.0.1 on 2024-02-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TextTech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("website", models.URLField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content_creators/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="TextTech.contentcreator",
                    ),
                ),
            ],
        ),
    ]
