# Generated by Django 5.0.1 on 2024-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TextTech", "0002_contentcreator_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="contentcreator",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
