# Generated by Django 5.0.1 on 2024-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TextTech", "0003_alter_blog_image_alter_contentcreator_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
    ]
