# Generated by Django 5.0.1 on 2024-02-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TextTech", "0007_userregister_address_userregister_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
