# Generated by Django 5.0.1 on 2024-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TextTech", "0009_alter_userregister_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Help",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
    ]
